export const SOCKET_EVENTS = {
  // Client -> Server Actions
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  TOGGLE_READY: 'TOGGLE_READY',
  START_GAME: 'START_GAME',
  CONFIRM_ROLE: 'CONFIRM_ROLE',
  SUBMIT_NIGHT_ACTION: 'SUBMIT_NIGHT_ACTION',
  CONFIRM_DAY_RESULT: 'CONFIRM_DAY_RESULT',
  SKIP_DISCUSSION: 'SKIP_DISCUSSION',
  SUBMIT_VOTE: 'SUBMIT_VOTE',
  CONFIRM_VOTE_RESULT: 'CONFIRM_VOTE_RESULT',
  PLAY_AGAIN: 'PLAY_AGAIN',

  // Server -> Client Broadcasts / Emissions
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  SEER_RESULT: 'SEER_RESULT',
  NIGHT_RESULT: 'NIGHT_RESULT',
  VOTE_RESULT: 'VOTE_RESULT',
  GAME_OVER: 'GAME_OVER',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  PLAYER_RECONNECTED: 'PLAYER_RECONNECTED',
  ERROR_MESSAGE: 'ERROR_MESSAGE'
};
