export const GAME_STATES = {
  LOBBY: 'LOBBY',
  ROLE_REVEAL: 'ROLE_REVEAL',
  NIGHT: 'NIGHT',
  DAY_RESULT: 'DAY_RESULT',
  DISCUSSION: 'DISCUSSION',
  VOTING: 'VOTING',
  VOTE_RESULT: 'VOTE_RESULT',
  GAME_OVER: 'GAME_OVER'
};
